#!/usr/bin/env python3
"""
Run Stable Audio Open Fine-Tuning

Purpose: Execute fine-tuning on ARAUS dataset using the official stable-audio-tools
training script.

Usage:
    python 03_run_training.py --config config_sao_base.yaml
    python 03_run_training.py --config config_sao_base.yaml --resume-from checkpoints/checkpoint_step_500

NOTE: This script uses the built-in `python -m train` command from stable-audio-tools.
The actual training is handled by the official training implementation.

Output:
    checkpoints/checkpoint_step_*.pt (model checkpoints)
    logs/ (training logs and metrics)
"""

import argparse
import sys
import subprocess
from pathlib import Path
import json
from datetime import datetime


def run_training(config_path, resume_from=None, device="cuda"):
    """
    Run training using stable-audio-tools built-in training command.

    Args:
        config_path: Path to training config YAML
        resume_from: Optional checkpoint to resume from
        device: Device to use (cuda or cpu)
    """
    config_path = Path(config_path)

    if not config_path.exists():
        print(f"❌ Config file not found: {config_path}")
        return False

    print("\n" + "="*70)
    print("Run: Stable Audio Open Fine-Tuning on ARAUS Dataset")
    print("="*70 + "\n")

    print(f"✓ Configuration: {config_path.absolute()}")
    print(f"  Using: stable-audio-tools built-in training")

    # Build the training command
    cmd = [
        sys.executable, "-m", "train",
        "--config", str(config_path),
    ]

    # Add resume checkpoint if provided
    if resume_from:
        resume_path = Path(resume_from)
        if not resume_path.exists():
            print(f"❌ Checkpoint not found: {resume_path}")
            return False
        cmd.extend(["--resume-from", str(resume_path)])
        print(f"  Resuming from: {resume_path.absolute()}")

    print("\n--- Starting Training ---")
    print(f"Command: {' '.join(cmd)}\n")

    try:
        # Run the training command
        result = subprocess.run(cmd, check=False)

        if result.returncode == 0:
            print("\n" + "="*70)
            print("✓ Training completed successfully!")
            print("="*70 + "\n")
            return True
        else:
            print("\n" + "="*70)
            print(f"❌ Training failed with return code {result.returncode}")
            print("="*70 + "\n")
            return False

    except KeyboardInterrupt:
        print("\n\n❌ Training interrupted by user")
        return False
    except Exception as e:
        print(f"\n❌ Error running training: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Run Stable Audio Open fine-tuning using stable-audio-tools",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python 03_run_training.py --config config_sao_base.yaml
  python 03_run_training.py --config config_sao_base.yaml --resume-from checkpoints/checkpoint_step_500.pt
  python 03_run_training.py --config config_sao_base.yaml --device cpu
        """
    )

    parser.add_argument(
        "--config",
        type=str,
        required=True,
        help="Path to training config YAML file (generated by 02_prepare_training_config.py)"
    )
    parser.add_argument(
        "--resume-from",
        type=str,
        default=None,
        help="Path to checkpoint to resume training from"
    )
    parser.add_argument(
        "--device",
        type=str,
        default="cuda",
        choices=["cuda", "cpu"],
        help="Device to use for training (default: cuda)"
    )

    args = parser.parse_args()

    # Run training
    success = run_training(args.config, args.resume_from, args.device)

    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
